import boto3
from botocore.exceptions import NoCredentialsError
from datetime import datetime
import os
startTime = datetime.now()
uploadStartTime = startTime.strftime("%H:%M:%S")
print("Current Time =", uploadStartTime)

ACCESS_KEY = '*********'
SECRET_KEY = '**************************'

filePath = input('Enter File path: ')
os.getcwd()
print(os.getcwd())
os.chdir(filePath)
print(os.getcwd())

startTime = datetime.now()
uploadStartTime = startTime.strftime("%H:%M:%S")
print("Current Time =", uploadStartTime)
bucket = 'pythonbucket12'
local_file = 'movieO.MP4'

# s3_file=

def upload_to_aws(local_file, bucket, s3_file):
    s3 = boto3.client('s3', aws_access_key_id=ACCESS_KEY,
                      aws_secret_access_key=SECRET_KEY)

    try:
        s3.upload_file(local_file, bucket, s3_file)
        print("Upload Successful")
        return True
    except FileNotFoundError:
        print("The file was not found")
        return False
    except NoCredentialsError:
        print("Credentials not available")
        return False




uploaded = upload_to_aws(local_file, bucket, 'movieO.MP4')

endTime = datetime.now()
uploadEndTime = endTime.strftime("%H:%M:%S")
print("End Time = ", uploadEndTime)


transferTime = endTime - startTime

print("Transfer Time = ", transferTime.total_seconds())
